source 'https://rubygems.org'

group :test do
  gem 'factory_bot_rails'
end

gemspec

gem 'blacklight-spotlight', git: 'https://github.com/projectblacklight/spotlight'

group :development, :test do
  gem 'solr_wrapper', '>= 0.3'
end
gem 'rsolr', '>= 1.0', '< 3'
gem 'bootstrap', '~> 4.0'
gem 'twitter-typeahead-rails', '0.11.1.pre.corejavascript'
gem 'jquery-rails'
gem 'devise'
gem 'devise-guests', '~> 0.8'
gem 'coffee-rails', '~> 4.2'
gem 'uglifier', '>= 1.3.0'
gem 'friendly_id'
gem 'riiif'
gem 'sitemap_generator'
gem 'blacklight-gallery', '~> 4.0'
gem 'openseadragon', '>= 0.2.0'
gem 'blacklight-oembed', '~> 1.0'
gem 'devise_invitable'
gem 'coffee-rails', '~> 4.2'
gem 'uglifier', '>= 1.3.0'
gem 'friendly_id'
gem 'riiif'
gem 'sitemap_generator'
gem 'blacklight-gallery', '~> 4.0'
gem 'openseadragon', '>= 0.2.0'
gem 'blacklight-oembed', '~> 1.0'
gem 'devise_invitable'
